import { escapeHtml } from '../lib/security';
import { portalLayout, portalMarkdown } from './portal-layout';
import type { PortalContent } from '../lib/portal-generator';
import type { PriceQuote } from '../lib/prices';

export interface PortalMemoInput {
  ticker: string;
  company: string;
  content: PortalContent;
  quote: PriceQuote | null;
  filing_10k_url: string | null;
  filing_10k_date: string | null;
  generated_at: string;
}

export function renderPortalMemo(input: PortalMemoInput): string {
  const { ticker, company, content, quote, filing_10k_url, filing_10k_date, generated_at } = input;
  const price = quote ? `$${quote.price.toFixed(2)}` : '—';
  const asOf = quote?.as_of ? quote.as_of.slice(0, 10) : '';

  const body = `
<main class="portal-narrow">
  <div class="page-eyebrow">Investment Memo · Levin Capital Strategies</div>
  <h1>${escapeHtml(company)} <span style="color:var(--text-muted);font-weight:500">(${escapeHtml(ticker)})</span></h1>
  <div class="page-subtitle">${asOf ? `As of ${asOf}` : 'Live brief'} · Institutional Research</div>
  <div class="page-tagline">${escapeHtml(content.tagline)}.</div>
  <div class="meta-strip">
    <div class="cell"><div class="lbl">Price</div><div class="val">${price}</div></div>
    <div class="cell"><div class="lbl">Price Target</div><div class="val gold">${escapeHtml((content.consensus.ourPt || '—').split('—')[0].trim())}</div></div>
    <div class="cell"><div class="lbl">Analyst</div><div class="val">LCS</div></div>
    <div class="cell"><div class="lbl">Generated</div><div class="val" style="font-size:14px">${escapeHtml(generated_at.slice(0,10))}</div></div>
  </div>

  <nav class="memo-toc" aria-label="Table of contents">
    <strong>Contents</strong>
    <a href="#summary">Business Summary</a>
    <a href="#scqa">Situation / Complication / Question / Answer</a>
    <a href="#bullbear">Bulls & Bears</a>
    <a href="#valuation">Valuation</a>
    <a href="#diligence">Questions for Management</a>
  </nav>

  <div class="bluf">
    <strong>The call:</strong> ${escapeHtml(content.answer ? stripMdMarks(content.answer).slice(0, 400) : content.tagline + '.')}
  </div>

  <div class="kicker">§ I — Business Summary</div>
  <h2 id="summary">${escapeHtml(company)} at a glance</h2>
  ${portalMarkdown(content.businessSummary)}

  <div class="kicker">§ II — SCQA</div>
  <h2 id="scqa">Situation, Complication, Question, Answer</h2>
  <h3>Situation</h3>
  ${portalMarkdown(content.situation)}
  <h3>Complication</h3>
  ${portalMarkdown(content.complication)}
  <h3>The Central Question</h3>
  ${portalMarkdown(content.centralQuestion)}
  <h3>Our Answer</h3>
  ${portalMarkdown(content.answer)}

  <div class="kicker">§ III — Bulls and Bears</div>
  <h2 id="bullbear">Bulls & Bears</h2>
  <div class="bull-bear">
    <div class="bb-card bull">
      <h3>Bull Case</h3>
      <ul>${content.bullPoints.map(b => `<li>${portalMarkdown(b, true)}</li>`).join('')}</ul>
    </div>
    <div class="bb-card bear">
      <h3>Bear Case</h3>
      <ul>${content.bearPoints.map(b => `<li>${portalMarkdown(b, true)}</li>`).join('')}</ul>
    </div>
  </div>

  <div class="kicker">§ IV — Valuation</div>
  <h2 id="valuation">How we frame value</h2>
  ${portalMarkdown(content.valuationNote)}

  ${content.diligenceQuestions.length > 0 ? `
  <div class="kicker">§ V — Diligence</div>
  <h2 id="diligence">Questions for Management</h2>
  <div class="diligence">
    ${content.diligenceQuestions.map(d => `
      <div class="dq">
        <div class="dq-q">${escapeHtml(d.q)}</div>
        <div class="dq-why">${escapeHtml(d.rationale)}</div>
      </div>
    `).join('')}
  </div>
  ` : ''}

  <p class="disclaimer"><strong>Sources:</strong>
  ${filing_10k_url ? `<a href="${filing_10k_url}" target="_blank" rel="noopener">10-K (${escapeHtml(filing_10k_date || '')})</a> · ` : ''}
  Live quotes via Yahoo Finance. This memo is automatically generated by Levin Capital Strategies' research platform from SEC primary sources. Not investment advice.</p>
</main>
`;

  return portalLayout({
    ticker, company, activePage: 'memo', price, asOf,
    title: `${ticker} Investment Memo · LCS Research`,
    body,
    pageStyles: `
.memo-toc{position:static;background:var(--surface);border:1px solid var(--border-light);border-radius:10px;padding:20px 24px;margin:28px 0 36px}
.memo-toc strong{display:block;font-family:'Inter',sans-serif;font-size:10px;letter-spacing:2px;color:var(--gold);font-weight:700;text-transform:uppercase;margin-bottom:12px}
.memo-toc a{display:inline-block;margin-right:16px;margin-bottom:6px;font-family:'Inter',sans-serif;font-size:13px;color:var(--heading);font-weight:500;border-bottom:1px dotted var(--border)}
.memo-toc a:hover{color:var(--gold)}

.bull-bear{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:24px 0 36px}
.bb-card{background:var(--surface);border:1px solid var(--border-light);border-radius:10px;padding:22px}
.bb-card.bull{border-top:3px solid var(--green)}
.bb-card.bear{border-top:3px solid var(--red)}
.bb-card h3{font-size:12px;letter-spacing:2px;margin-top:0;color:var(--heading)}
.bb-card ul{padding-left:18px;margin:10px 0 0}
.bb-card li{font-size:15px;line-height:1.55;margin-bottom:10px;color:var(--text);list-style-type:disc}

.diligence{margin:20px 0 32px}
.dq{padding:16px 0;border-bottom:1px solid var(--border-light)}
.dq:last-child{border-bottom:none}
.dq-q{font-family:'Merriweather',serif;font-size:16px;font-weight:700;color:var(--heading);margin-bottom:4px}
.dq-why{font-family:'Inter',sans-serif;font-size:13px;color:var(--text-muted);line-height:1.5}
.dq-why::before{content:"Why: ";color:var(--gold);font-weight:600}

@media(max-width:720px){
  .bull-bear{grid-template-columns:1fr;gap:14px}
}
`,
  });
}

function stripMdMarks(s: string): string {
  return s.replace(/\*\*/g, '').replace(/\[([A-Za-z0-9\-\s]+)\]/g, '').replace(/\s+/g, ' ').trim();
}
