export function renderWorkspace(role: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Today’s Decisions · The Signal</title>
<style>body{background:#faf7f0;color:#13243c;font:16px/1.55 Georgia,serif;margin:0}header,main{max-width:1140px;margin:auto;padding:24px}header{border-bottom:2px solid #b8973e}h1{font-size:40px;margin:0}nav{display:flex;gap:20px;flex-wrap:wrap}a{color:#742432}button,input,select,textarea{font:inherit;padding:9px;border:1px solid #68645e;border-radius:3px;background:white;color:#13243c}button{cursor:pointer;background:#13243c;color:white}button:disabled{opacity:.5}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #a5530c;outline-offset:3px}label{display:flex;flex-direction:column;gap:4px}form,.filters{display:flex;gap:12px;flex-wrap:wrap;align-items:end}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:16px}article,section.panel{border:1px solid #c5bfb2;padding:20px;margin:16px 0}small,.muted{color:#585851}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:10px;border-bottom:1px solid #c5bfb2}table a{overflow-wrap:anywhere}.scroll{overflow:auto}textarea{width:100%;box-sizing:border-box;min-height:140px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:15px/1.5 Georgia,serif}#message{padding:12px;border-left:4px solid #b8973e;min-height:24px}.wide{width:100%}.compare{display:grid;grid-template-columns:1fr 1fr;gap:20px}[hidden]{display:none!important}@media(max-width:650px){header,main{padding:16px}h1{font-size:30px}.compare{grid-template-columns:1fr}} </style></head><body>
<header><p>THE SIGNAL · RESEARCH WORKSPACE</p><h1>Today’s Decisions</h1><p>Latest recorded views, evidence and the next research question.</p><nav><a href="https://research.levincap.com/">Editorial home</a><a href="/research">Research Desk</a><a href="#etf">ETF → ideas</a><a href="#drafts">Review queue</a></nav></header>
<main><p id="message" role="status" aria-live="polite">Loading the published catalog…</p><p class="muted">Team access · ${role === "reviewer" ? "Reviewer" : "Analyst"} · No live prices or automatic investment alerts. Missing dates and review approvals are not inferred.</p>
<section aria-label="Decision filters"><form id="filters"><label>Company / ticker<input name="q" type="search"></label><label>Stance<select name="stance"><option value="">All stances</option><option>ACCUMULATE</option><option>PASS</option></select></label><label>Document type<select name="type"><option value="">All types</option><option value="earnings">Earnings</option><option value="pitch">Pitch</option><option value="idea">Idea</option><option value="product">Product</option></select></label><label>Sector<input name="sector"></label><label>Revised since<input name="since" type="date"></label><label>Sort<select name="sort"><option value="updated">Latest update</option><option value="catalyst">Next dated catalyst</option></select></label><label>Layout<select name="layout"><option value="cards">Cards</option><option value="table">Table</option></select></label><button>Apply</button></form></section>
<h2>Current company views</h2><div id="views" class="cards"></div><h2>Company history & documents</h2><p id="scope" class="muted"></p><div id="documents"></div>
<section id="etf" class="panel"><h2>Start with an ETF. Surface a research question.</h2><p>Search saved holdings by ETF ticker, then filter companies. Weight is a discovery criterion, not an investment score. Cash, derivatives and unresolved identities cannot become company candidates.</p><form id="etf-search"><label>ETF ticker<input name="etf" placeholder="e.g. XLI" maxlength="15"></label><button>Search snapshots</button></form><label>Holdings snapshot<select id="snapshot"><option value="">Select a dated snapshot</option></select></label><label>Filter underlying companies<input id="holding-search" type="search"></label><p id="snapshot-info"></p><div id="holdings"></div>
<details><summary>Import an issuer/provider holdings snapshot</summary><p>Paste normalized JSON from a source you checked. Required: etf, asOf (YYYY-MM-DD or null), provider, sourceUrl, completeness (full/partial/unknown), holdings. Each holding requires ticker (or null), company, weight (percent or null), currency (or null), and assetType (equity/cash/derivative/unresolved). Unknown identity must remain unresolved. Imported metadata is analyst-supplied, not independently verified.</p><label>Holdings JSON<textarea id="import-data" spellcheck="false"></textarea></label><button id="import">Save snapshot</button></details></section>
<section class="panel"><h2>Draft an earnings update</h2><p>Uses the existing Research Desk earnings workflow. Sources and draft are saved first; generation never grants review or publication.</p><form id="create-draft"><label>Ticker<input name="ticker" required maxlength="15" list="covered"></label><datalist id="covered"></datalist><label>Title<input name="title" required maxlength="200"></label><label class="wide">Primary source URLs (one per line)<textarea name="sources" required></textarea></label><label class="wide">Source material<textarea name="sourceText" required maxlength="60000"></textarea></label><button>Save draft</button></form><p id="candidate" class="muted">No ETF candidate selected.</p></section>
<section id="drafts" class="panel"><h2>Review queue & company timeline</h2><button id="refresh">Refresh queue</button><div id="queue"></div><div id="editor" hidden><h3 id="revision-title"></h3><p id="revision-meta"></p><div id="revision-sources"></div><div class="compare"><div><h4>Previous published revision</h4><pre id="previous"></pre></div><div><h4>Selected revision</h4><label>Draft body<textarea id="body"></textarea></label></div></div><p id="change-summary"></p><div class="filters"><button data-action="generate">Generate / retry</button><button data-action="recover">Recover timed-out generation</button><button data-action="edit">Save edits (clears approval)</button><button data-action="submit">Submit for review</button><button data-action="approve">Approve this revision</button><button data-action="publish">Publish approved revision</button><button data-action="withdraw">Withdraw</button></div><label><span><input type="checkbox" id="confirm-public"> I confirm this approved revision is suitable for public release.</span></label><p>Publication is disabled until the production release gate is explicitly enabled. Published bodies are immutable. Create a new revision for further changes.</p></div></section></main>
<script>
const base='/research/workspace';let catalog={documents:[],currentViews:[]},snapshots=[],selected=null,revision=null,candidate=null;
const $=s=>document.querySelector(s),esc=v=>String(v??'Not recorded').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const message=s=>$('#message').textContent=s;
async function api(path,body){const r=await fetch(new URL(base+path,location.origin),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data}
function guarded(fn){return async e=>{e?.preventDefault();try{await fn(e)}catch(err){message(err.message)}}}
function render(){const p=new URLSearchParams(location.search),q=(p.get('q')||'').toLowerCase(),sector=(p.get('sector')||'').toLowerCase(),stance=p.get('stance'),since=p.get('since'),type=p.get('type');
const views=catalog.currentViews.filter(v=>(v.ticker+' '+v.company).toLowerCase().includes(q)&&v.sector.toLowerCase().includes(sector)&&(!stance||v.stance===stance)&&(!since||v.effectiveDate>=since)).sort((a,b)=>p.get('sort')==='catalyst'?(a.nextCatalyst?.date||'9999').localeCompare(b.nextCatalyst?.date||'9999'):b.effectiveDate.localeCompare(a.effectiveDate));
$('#views').className=p.get('layout')==='table'?'scroll':'cards';$('#views').innerHTML=p.get('layout')==='table'?'<table><thead><tr><th>Company</th><th>View / effective date</th><th>Next catalyst</th><th>What changed</th></tr></thead><tbody>'+views.map(v=>'<tr><td><a href="'+esc(v.canonicalUrl)+'">'+esc(v.ticker)+'</a></td><td>'+esc(v.stance)+' · '+esc(v.effectiveDate)+'</td><td>'+esc(v.nextCatalyst?.date)+'</td><td>'+esc(v.change)+'</td></tr>').join('')+'</tbody></table>':views.map(v=>'<article><small>Latest recorded view · '+esc(v.effectiveDate)+'</small><h3><a href="'+esc(v.canonicalUrl)+'">'+esc(v.ticker)+' · '+esc(v.company)+'</a></h3><p>'+esc(v.stance)+' · Analyst review '+(v.reviewedAt?esc(v.reviewedAt):'not recorded')+'</p><p>'+esc(v.change)+'</p><p>Reference '+esc(v.currency)+' '+esc(v.referencePrice)+' · '+esc(v.priceDate)+' (not live)</p><p>'+esc(v.decisionLevels)+'</p><p>Next dated catalyst: '+esc(v.nextCatalyst?.date)+'<br>Next review: '+esc(v.nextReviewDate)+'</p><a href="'+esc(v.modelUrl)+'">Versioned model</a></article>').join('');if(!views.length)$('#views').textContent='No current views match these filters.';
const docs=catalog.documents.map(d=>({...d,displayDate:d.revisedAt||d.recordedDate||''})).filter(d=>(d.ticker+' '+d.title).toLowerCase().includes(q)&&d.sector.toLowerCase().includes(sector)&&(!type||d.documentType===type)&&(!since||d.displayDate>=since)&&(!stance||catalog.currentViews.some(v=>v.ticker===d.ticker&&v.stance===stance))).sort((a,b)=>b.displayDate.localeCompare(a.displayDate));$('#documents').innerHTML=docs.length?'<details><summary>'+docs.length+' documents · expand company history</summary><ul>'+docs.map(d=>'<li><a href="'+esc(d.canonicalUrl)+'">'+esc(d.title)+'</a> · '+esc(d.documentType)+' · '+(d.revisedAt?'revised ':'recorded date ')+esc(d.displayDate)+'<p class="muted">'+esc(d.summary.slice(0,200))+'</p></li>').join('')+'</ul></details>':'No documents match these filters.';$('#scope').textContent=catalog.scope;$('#covered').innerHTML=[...new Set(catalog.documents.map(d=>d.ticker).filter(Boolean))].map(t=>'<option value="'+esc(t)+'">').join('');}
$('#filters').onsubmit=guarded(async()=>{const p=new URLSearchParams();for(const [k,v]of new FormData($('#filters')))if(v)p.set(k,v);history.pushState(null,'','?'+p);render()});window.onpopstate=()=>{hydrateFilters();render()};function hydrateFilters(){const p=new URLSearchParams(location.search);for(const el of $('#filters').elements)if(el.name)el.value=p.get(el.name)||({sort:'updated',layout:'cards'}[el.name]||'')}
async function loadETFs(etf=''){snapshots=(await api('/api/etfs?etf='+encodeURIComponent(etf))).snapshots;$('#snapshot').innerHTML='<option value="">Select snapshot ('+snapshots.length+')</option>'+snapshots.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.etf)+' · '+esc(s.as_of)+' · '+esc(s.provider)+' · '+esc(s.completeness)+'</option>').join('');selected=null;renderHoldings()}
$('#etf-search').onsubmit=guarded(async()=>{await loadETFs(new FormData($('#etf-search')).get('etf'));message(snapshots.length?'Select a snapshot.':'No saved holdings for this ETF. Import a dated issuer/provider snapshot; no holdings have been fabricated.')});
$('#snapshot').onchange=()=>{selected=snapshots.find(s=>s.id===$('#snapshot').value)||null;renderHoldings()};$('#holding-search').oninput=renderHoldings;
function renderHoldings(){if(!selected){$('#holdings').textContent='No snapshot selected.';$('#snapshot-info').textContent='';return}const s=JSON.parse(selected.data_json),q=$('#holding-search').value.toLowerCase(),covered=new Set(catalog.documents.map(d=>d.ticker));$('#snapshot-info').textContent='Holdings as of '+(s.asOf||'not recorded')+' · retrieved '+selected.retrieved_at+' · '+s.completeness+' snapshot · source metadata supplied by analyst. No holdings-change comparison or live price signal.';const rows=s.holdings.map((h,i)=>({...h,index:i})).filter(h=>(h.ticker+' '+h.company).toLowerCase().includes(q)).sort((a,b)=>(b.weight??-1)-(a.weight??-1));$('#holdings').innerHTML='<p><a href="'+esc(s.sourceUrl)+'" target="_blank" rel="noopener noreferrer">'+esc(s.provider)+' source</a></p><div class="scroll"><table><thead><tr><th>Company / asset</th><th>Weight</th><th>Why surfaced</th><th>Next step</th></tr></thead><tbody>'+rows.map(h=>'<tr><td>'+esc(h.ticker)+' · '+esc(h.company)+'</td><td>'+esc(h.weight)+(h.weight===null?'':'%')+'</td><td>'+esc(h.assetType)+' · '+(covered.has(h.ticker)?'Existing coverage':'No catalog coverage found')+'</td><td>'+(h.assetType==='equity'&&h.ticker?'<button data-holding="'+h.index+'">Research candidate</button>':'Not a resolved company')+'</td></tr>').join('')+'</tbody></table></div>';for(const button of document.querySelectorAll('[data-holding]'))button.onclick=()=>{const h=s.holdings[Number(button.dataset.holding)];candidate={ticker:h.ticker,snapshotId:selected.id};$('#create-draft [name=ticker]').value=h.ticker;$('#create-draft [name=title]').value=h.ticker+' earnings update';$('#create-draft [name=sources]').value=s.sourceUrl;$('#candidate').textContent='Candidate '+h.ticker+' from '+s.etf+' snapshot '+selected.id+'. This is not a house recommendation.';$('#create-draft').scrollIntoView({behavior:'smooth'})}}
$('#import').onclick=guarded(async()=>{const saved=await api('/api/etfs',JSON.parse($('#import-data').value));await loadETFs();$('#snapshot').value=saved.id;selected=snapshots.find(s=>s.id===saved.id);renderHoldings();message('Holdings snapshot saved durably.')});
let draftKey=crypto.randomUUID();$('#create-draft').onsubmit=guarded(async()=>{const b=Object.fromEntries(new FormData($('#create-draft')));b.ticker=b.ticker.toUpperCase();b.sources=b.sources.split(/\\n/).map(s=>s.trim()).filter(Boolean);b.idempotencyKey=draftKey;if(candidate?.ticker===b.ticker)b.snapshotId=candidate.snapshotId;const saved=await api('/api/revisions',b);draftKey=crypto.randomUUID();await queue();await openRevision(saved.id);message('Draft and sources saved. Generate when ready.');});
async function queue(){const rows=(await api('/api/revisions')).revisions;$('#queue').innerHTML=rows.length?'<ul>'+rows.map(r=>'<li><button data-revision="'+esc(r.id)+'">'+esc(r.ticker)+' · '+esc(r.title)+'</button> '+esc(r.status)+' · revised '+esc(r.revised_at)+(r.error_code?' · Generation failed; retry available':'')+'</li>').join('')+'</ul>':'No drafts awaiting review. No overdue dates have been inferred.';for(const b of document.querySelectorAll('[data-revision]'))b.onclick=guarded(()=>openRevision(b.dataset.revision))}
async function openRevision(id){const data=await api('/api/revisions/'+id);revision=data.revision;$('#editor').hidden=false;$('#revision-title').textContent=revision.title;$('#revision-meta').textContent=revision.status+' · version '+revision.version+' · reviewed '+(revision.reviewed_at||'not recorded');$('#body').value=revision.body;$('#body').disabled=['published','withdrawn','generating'].includes(revision.status);$('#previous').textContent=data.previous?.body||'No previous published workspace revision. Consult the catalog for earlier editorial research.';$('#change-summary').textContent=data.previous?(data.previous.body===revision.body?'Body unchanged from previous published revision.':'Body differs from previous published revision; review the full comparison above.'):'First workspace revision; no generated change claim.';const source=JSON.parse(revision.source_json);$('#revision-sources').innerHTML='<h4>Saved sources</h4><ul>'+source.urls.map(u=>'<li><a href="'+esc(u)+'">'+esc(u)+'</a></li>').join('')+'</ul><details><summary>Saved source material</summary><pre>'+esc(source.text)+'</pre></details>';$('#editor').scrollIntoView({behavior:'smooth'})}
for(const b of document.querySelectorAll('[data-action]'))b.onclick=guarded(async()=>{if(!revision)return;const action=b.dataset.action;b.disabled=true;message(action==='generate'?'Generating with the Research Desk. Sources are saved; this can take several minutes.':'Saving…');try{await api('/api/revisions/'+revision.id+'/'+action,{version:revision.version,body:$('#body').value,confirmPublic:$('#confirm-public').checked});await openRevision(revision.id);await queue();message('Revision updated.')}finally{b.disabled=false}});
$('#refresh').onclick=guarded(queue);hydrateFilters();Promise.all([api('/api/catalog').then(c=>{catalog=c;render();message('Catalog loaded. Reference prices are historical; analyst-review gaps are shown explicitly.')}),queue()]).catch(err=>message(err.message));
</script></body></html>`;
}
